---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-02-17 - 10:09:14 +0000
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/version: 1.0.0
  name: payment
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: payment
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-02-17 - 10:09:14 +0000
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/version: 1.0.0
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-02-17 - 10:09:14 +0000
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/lordofthejars/payment:1.0.0
          imagePullPolicy: Always
          name: payment
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
